import { CompanyState, Employee } from "../types/CompanyState";

export const defaultEmployee: Employee = {
  lastName: "",
  firstName: "",
  position: "",
  isSelected: false,
  id: Date.now() + Math.random(),
  companyId: 1,
};

export const defaultCompany = {
  name: "",
  address: "",
  isSelected: false,
  id: Date.now() + Math.random(),
  employee: [],
};

export const initialState: CompanyState = {
  companies: [
    {
      id: 1,
      name: "Company 1",
      address: "Address 1",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 1,
          companyId: 1,
          lastName: "Last Name 1",
          firstName: "First Name 1",
          position: "Position 1",
        },
        {
          isSelected: false,
          id: 2,
          companyId: 1,
          lastName: "Last Name 2",
          firstName: "First Name 2",
          position: "Position 2",
        },
      ],
    },
    {
      id: 2,
      name: "Компания 2",
      address: "Адрес 2",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 3,
          companyId: 2,
          lastName: "Фамилия 1",
          firstName: "Имя 1",
          position: "Должность 1",
        },
        {
          isSelected: false,
          id: 4,
          companyId: 2,
          lastName: "Фамилия 2",
          firstName: "Имя 2",
          position: "Должность 2",
        },
      ],
    },
    {
      id: 3,
      name: "Компания 3",
      address: "Адрес 3",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 5,
          companyId: 3,
          lastName: "Иванов",
          firstName: "Алексей",
          position: "Разработчик",
        },
        {
          isSelected: false,
          id: 6,
          companyId: 3,
          lastName: "Петрова",
          firstName: "Елена",
          position: "Менеджер по продажам",
        },
      ],
    },
    {
      id: 4,
      name: "ООО РосПром",
      address: "Москва, ул. Промышленная, 123",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 7,
          companyId: 4,
          lastName: "Смирнов",
          firstName: "Андрей",
          position: "Инженер-конструктор",
        },
        {
          isSelected: false,
          id: 8,
          companyId: 4,
          lastName: "Кузнецова",
          firstName: "Мария",
          position: "Финансовый аналитик",
        },
      ],
    },
    {
      id: 5,
      name: "Производственное объединение",
      address: "Санкт-Петербург, ул. Промышленная, 567",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 9,
          companyId: 5,
          lastName: "Николаев",
          firstName: "Александра",
          position: "Инженер-технолог",
        },
        {
          isSelected: false,
          id: 10,
          companyId: 5,
          lastName: "Сергеев",
          firstName: "Иван",
          position: "Логист",
        },
      ],
    },
    {
      id: 6,
      name: "Технологическая компания",
      address: "Екатеринбург, ул. Техническая, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 11,
          companyId: 6,
          lastName: "Козлов",
          firstName: "Ольга",
          position: "Аналитик по данных",
        },
        {
          isSelected: false,
          id: 12,
          companyId: 6,
          lastName: "Морозов",
          firstName: "Дмитрий",
          position: "Инженер-программист",
        },
      ],
    },
    {
      id: 7,
      name: "Научно-исследовательский институт",
      address: "Новосибирск, ул. Научная, 456",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 13,
          companyId: 7,
          lastName: "Белова",
          firstName: "Екатерина",
          position: "Научный сотрудник",
        },
        {
          isSelected: false,
          id: 14,
          companyId: 7,
          lastName: "Кудряшов",
          firstName: "Артем",
          position: "Исследователь-биолог",
        },
      ],
    },
    {
      id: 8,
      name: "IT-консалтинговая фирма",
      address: "Казань, ул. Инновационная, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 15,
          companyId: 8,
          lastName: "Ахметов",
          firstName: "Рустам",
          position: "IT-консультант",
        },
        {
          isSelected: false,
          id: 16,
          companyId: 8,
          lastName: "Султанова",
          firstName: "Лейла",
          position: "Проектный менеджер",
        },
      ],
    },
    {
      id: 9,
      name: "Медицинский центр Здоровье",
      address: "Сочи, ул. Здоровая, 101",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 17,
          companyId: 9,
          lastName: "Попов",
          firstName: "Анастасия",
          position: "Врач-терапевт",
        },
        {
          isSelected: false,
          id: 18,
          companyId: 9,
          lastName: "Медведев",
          firstName: "Игорь",
          position: "Медсестра",
        },
      ],
    },
    {
      id: 10,
      name: "Рекламное агентство Креатив",
      address: "Краснодар, ул. Идеи, 555",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 19,
          companyId: 10,
          lastName: "Соколова",
          firstName: "Елена",
          position: "Креативный директор",
        },
        {
          isSelected: false,
          id: 20,
          companyId: 10,
          lastName: "Петров",
          firstName: "Александр",
          position: "Графический дизайнер",
        },
      ],
    },
    {
      id: 11,
      name: "Производственная компания СтройПрогресс",
      address: "Воронеж, ул. Строительная, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 21,
          companyId: 11,
          lastName: "Иванов",
          firstName: "Артем",
          position: "Инженер-строитель",
        },
        {
          isSelected: false,
          id: 22,
          companyId: 11,
          lastName: "Семенова",
          firstName: "Марина",
          position: "Бухгалтер",
        },
      ],
    },
    {
      id: 12,
      name: "Туристическое агентство Путешествие",
      address: "Самара, ул. Путевая, 123",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 23,
          companyId: 12,
          lastName: "Князев",
          firstName: "Олег",
          position: "Турагент",
        },
        {
          isSelected: false,
          id: 24,
          companyId: 12,
          lastName: "Белкина",
          firstName: "Анна",
          position: "Менеджер по бронированию",
        },
      ],
    },
    {
      id: 13,
      name: "Дизайн-студия Креативный Взгляд",
      address: "Ростов-на-Дону, ул. Искусства, 456",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 25,
          companyId: 13,
          lastName: "Попович",
          firstName: "Анастасия",
          position: "Графический дизайнер",
        },
        {
          isSelected: false,
          id: 26,
          companyId: 13,
          lastName: "Михайлов",
          firstName: "Денис",
          position: "Иллюстратор",
        },
      ],
    },
    {
      id: 14,
      name: "Кофейня Уютный Аромат",
      address: "Уфа, ул. Ароматная, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 27,
          companyId: 14,
          lastName: "Савельев",
          firstName: "Алиса",
          position: "Бариста",
        },
        {
          isSelected: false,
          id: 28,
          companyId: 14,
          lastName: "Тимофеев",
          firstName: "Максим",
          position: "Менеджер по обслуживанию",
        },
      ],
    },
    {
      id: 15,
      name: "Автомобильный сервис Авто-Мастер",
      address: "Красноярск, ул. Механики, 101",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 29,
          companyId: 15,
          lastName: "Васнецов",
          firstName: "Дмитрий",
          position: "Механик",
        },
        {
          isSelected: false,
          id: 30,
          companyId: 15,
          lastName: "Лебедева",
          firstName: "Татьяна",
          position: "Администратор сервиса",
        },
      ],
    },
    {
      id: 16,
      name: "Магазин Электроника",
      address: "Томск, ул. Техническая, 222",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 31,
          companyId: 16,
          lastName: "Петров",
          firstName: "Игорь",
          position: "Продавец-консультант",
        },
        {
          isSelected: false,
          id: 32,
          companyId: 16,
          lastName: "Кузнецова",
          firstName: "Мария",
          position: "Специалист по технической поддержке",
        },
      ],
    },
    {
      id: 17,
      name: "Ресторан Гастроном",
      address: "Иркутск, ул. Кулинарная, 333",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 33,
          companyId: 17,
          lastName: "Соловьев",
          firstName: "Анна",
          position: "Шеф-повар",
        },
        {
          isSelected: false,
          id: 34,
          companyId: 17,
          lastName: "Козлов",
          firstName: "Андрей",
          position: "Официант",
        },
      ],
    },
    {
      id: 18,
      name: "Фитнес-центр Здоровая Форма",
      address: "Ульяновск, ул. Спортивная, 77",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 35,
          companyId: 18,
          lastName: "Игнатьева",
          firstName: "Ольга",
          position: "Инструктор по фитнесу",
        },
        {
          isSelected: false,
          id: 36,
          companyId: 18,
          lastName: "Петров",
          firstName: "Антон",
          position: "Персональный тренер",
        },
      ],
    },
    {
      id: 19,
      name: "Книжный магазин Читай-Гуляй",
      address: "Тула, ул. Литературная, 123",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 37,
          companyId: 19,
          lastName: "Сидорова",
          firstName: "Елена",
          position: "Книготорговец",
        },
        {
          isSelected: false,
          id: 38,
          companyId: 19,
          lastName: "Куликов",
          firstName: "Иван",
          position: "Библиотекарь",
        },
      ],
    },
    {
      id: 20,
      name: "Агентство Недвижимости Ключ",
      address: "Калининград, ул. Застройщиков, 456",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 39,
          companyId: 20,
          lastName: "Воронов",
          firstName: "Наталья",
          position: "Риэлтор",
        },
        {
          isSelected: false,
          id: 40,
          companyId: 20,
          lastName: "Соколов",
          firstName: "Артем",
          position: "Юрист по недвижимости",
        },
      ],
    },
    {
      id: 21,
      name: "Интернет-магазин ЭлектроГаджеты",
      address: "Ярославль, ул. Электронная, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 41,
          companyId: 21,
          lastName: "Гаджиев",
          firstName: "Роман",
          position: "Менеджер по продажам",
        },
        {
          isSelected: false,
          id: 42,
          companyId: 21,
          lastName: "Михайлова",
          firstName: "Алина",
          position: "Специалист по обслуживанию",
        },
      ],
    },
    {
      id: 22,
      name: "Химическая лаборатория НаукаХим",
      address: "Курск, ул. Химическая, 101",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 43,
          companyId: 22,
          lastName: "Павлов",
          firstName: "Евгений",
          position: "Химик-исследователь",
        },
        {
          isSelected: false,
          id: 44,
          companyId: 22,
          lastName: "Сергеева",
          firstName: "Оксана",
          position: "Лаборант",
        },
      ],
    },
    {
      id: 23,
      name: "Театр Комедии и Драмы",
      address: "Нижний Новгород, ул. Театральная, 555",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 45,
          companyId: 23,
          lastName: "Антонов",
          firstName: "Сергей",
          position: "Режиссер",
        },
        {
          isSelected: false,
          id: 46,
          companyId: 23,
          lastName: "Петрова",
          firstName: "Людмила",
          position: "Актриса",
        },
      ],
    },
    // Объект 24
    {
      id: 24,
      name: "Рекламное агентство Свет Идей",
      address: "Улан-Удэ, ул. Идеальная, 888",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 47,
          companyId: 24,
          lastName: "Иванов",
          firstName: "Артем",
          position: "Креативный директор",
        },
        {
          isSelected: false,
          id: 48,
          companyId: 24,
          lastName: "Сидорова",
          firstName: "Екатерина",
          position: "PR-менеджер",
        },
      ],
    },
    // Объект 25
    {
      id: 25,
      name: "Магазин детских игрушек Радуга",
      address: "Барнаул, ул. Игровая, 333",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 49,
          companyId: 25,
          lastName: "Павлова",
          firstName: "Анна",
          position: "Продавец-консультант",
        },
        {
          isSelected: false,
          id: 50,
          companyId: 25,
          lastName: "Козлов",
          firstName: "Иван",
          position: "Старший кассир",
        },
      ],
    },
    // Объект 26
    {
      id: 26,
      name: "Спортивный клуб Энергия",
      address: "Тверь, ул. Спортивная, 999",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 51,
          companyId: 26,
          lastName: "Беляков",
          firstName: "Денис",
          position: "Тренер по фитнесу",
        },
        {
          isSelected: false,
          id: 52,
          companyId: 26,
          lastName: "Михайлова",
          firstName: "Елена",
          position: "Координатор мероприятий",
        },
      ],
    },
    // Объект 27
    {
      id: 27,
      name: "Агентство Путешествий Экзотика",
      address: "Рязань, ул. Путевая, 456",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 53,
          companyId: 27,
          lastName: "Ковалев",
          firstName: "Татьяна",
          position: "Турагент",
        },
        {
          isSelected: false,
          id: 54,
          companyId: 27,
          lastName: "Сидоров",
          firstName: "Игорь",
          position: "Менеджер по бронированию",
        },
      ],
    },
    // Объект 33
    {
      id: 33,
      name: "Ресторан Пикантные Вкусы",
      address: "Владивосток, ул. Гастрономическая, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 65,
          companyId: 33,
          lastName: "Иванов",
          firstName: "Алексей",
          position: "Шеф-повар",
        },
        {
          isSelected: false,
          id: 66,
          companyId: 33,
          lastName: "Смирнова",
          firstName: "Анна",
          position: "Официантка",
        },
      ],
    },
    // Объект 34
    {
      id: 34,
      name: "Агентство Недвижимости Домовладение",
      address: "Челябинск, ул. Домовладельческая, 555",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 67,
          companyId: 34,
          lastName: "Кузнецов",
          firstName: "Евгений",
          position: "Риэлтор",
        },
        {
          isSelected: false,
          id: 68,
          companyId: 34,
          lastName: "Петрова",
          firstName: "Алина",
          position: "Юрист по недвижимости",
        },
      ],
    },
    // Объект 35
    {
      id: 35,
      name: "Автомобильный дилерский центр Премьера",
      address: "Курган, ул. Автомобильная, 123",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 69,
          companyId: 35,
          lastName: "Соколов",
          firstName: "Денис",
          position: "Продавец-консультант",
        },
        {
          isSelected: false,
          id: 70,
          companyId: 35,
          lastName: "Иванова",
          firstName: "Екатерина",
          position: "Сервисный инженер",
        },
      ],
    },
    // Объект 36
    {
      id: 36,
      name: "Спортивный магазин СпортЛайф",
      address: "Ижевск, ул. Активная, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 71,
          companyId: 36,
          lastName: "Петров",
          firstName: "Александр",
          position: "Продавец-консультант",
        },
        {
          isSelected: false,
          id: 72,
          companyId: 36,
          lastName: "Смирнова",
          firstName: "Мария",
          position: "Кассир",
        },
      ],
    },
    // Объект 37
    {
      id: 37,
      name: "Технопарк Инновации",
      address: "Тольятти, ул. Технологическая, 101",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 73,
          companyId: 37,
          lastName: "Иванова",
          firstName: "Анна",
          position: "Инженер-разработчик",
        },
        {
          isSelected: false,
          id: 74,
          companyId: 37,
          lastName: "Козлов",
          firstName: "Дмитрий",
          position: "Менеджер проектов",
        },
      ],
    }, // Объект 38
    {
      id: 38,
      name: "Кафе Сладкая Впечатление",
      address: "Кострома, ул. Десертная, 456",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 75,
          companyId: 38,
          lastName: "Петрова",
          firstName: "Ирина",
          position: "Шеф-кондитер",
        },
        {
          isSelected: false,
          id: 76,
          companyId: 38,
          lastName: "Сидоров",
          firstName: "Алексей",
          position: "Официант",
        },
      ],
    },
    // Объект 39
    {
      id: 39,
      name: "Салон Красоты Лучшая Форма",
      address: "Кемерово, ул. Ухоженная, 555",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 77,
          companyId: 39,
          lastName: "Иванова",
          firstName: "Мария",
          position: "Парикмахер-стилист",
        },
        {
          isSelected: false,
          id: 78,
          companyId: 39,
          lastName: "Петров",
          firstName: "Денис",
          position: "Мастер маникюра",
        },
      ],
    },
    // Объект 40
    {
      id: 40,
      name: "Интернет-магазин Эко-Товары",
      address: "Ульяновск, ул. Экологическая, 101",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 79,
          companyId: 40,
          lastName: "Сергеев",
          firstName: "Ольга",
          position: "Менеджер по продажам",
        },
        {
          isSelected: false,
          id: 80,
          companyId: 40,
          lastName: "Иванов",
          firstName: "Андрей",
          position: "Экологический консультант",
        },
      ],
    },
    // Объект 41
    {
      id: 41,
      name: "Ателье Модных Трендов",
      address: "Иркутск, ул. Модельная, 123",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 81,
          companyId: 41,
          lastName: "Петрова",
          firstName: "Алена",
          position: "Модельер",
        },
        {
          isSelected: false,
          id: 82,
          companyId: 41,
          lastName: "Сидоров",
          firstName: "Дмитрий",
          position: "Швея",
        },
      ],
    },
    // Объект 42
    {
      id: 42,
      name: "Агентство Интересные Путешествия",
      address: "Уфа, ул. Путевая, 789",
      isSelected: false,
      employee: [
        {
          isSelected: false,
          id: 83,
          companyId: 42,
          lastName: "Ковалева",
          firstName: "Татьяна",
          position: "Турагент",
        },
        {
          isSelected: false,
          id: 84,
          companyId: 42,
          lastName: "Иванов",
          firstName: "Алексей",
          position: "Менеджер по бронированию",
        },
      ],
    },
  ],
};
