export const employeesList = [
  {
    isSelected: false,
    id: 1,
    companyId: 1,
    lastName: "Last Name 1",
    firstName: "First Name 1",
    position: "Position 1",
  },
  {
    isSelected: false,
    id: 2,
    companyId: 1,
    lastName: "Last Name 2",
    firstName: "First Name 2",
    position: "Position 2",
  },
  {
    isSelected: false,
    id: 3,
    companyId: 2,
    lastName: "Last Name 3",
    firstName: "First Name 3",
    position: "Position 3",
  },
  {
    isSelected: false,
    id: 4,
    companyId: 2,
    lastName: "Last Name 4",
    firstName: "First Name 4",
    position: "Position 4",
  },
  {
    isSelected: false,
    id: 5,
    companyId: 2,
    lastName: "Last Name 5",
    firstName: "First Name 5",
    position: "Position 5",
  },
  {
    isSelected: false,
    id: 6,
    companyId: 3,
    lastName: "Last Name 6",
    firstName: "First Name 6",
    position: "Position 6",
  },
  {
    isSelected: false,
    id: 7,
    companyId: 3,
    lastName: "Last Name 7",
    firstName: "First Name 7",
    position: "Position 7",
  },
];
